name: Check If Repository Application Is Installed

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize

jobs:
  check-repo-installation:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: https://api.staging.allocator.tech
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: 'Allocators/**/*.json'

      - name: Check allocator bookkeeping URLs
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          failed=0
          failures=""

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "🔍 Processing $file"

            repo_url=$(jq -r '.application.allocation_bookkeeping // empty' "$file")

            if [[ "$repo_url" == https://github.com/* ]]; then
              owner=$(echo "$repo_url" | cut -d'/' -f4)
              repo=$(echo "$repo_url" | cut -d'/' -f5)
              echo "Found GitHub repo: $owner/$repo"

              echo "Checking installation status..."
              if curl -f -X GET "${BACKEND_URL}/allocator/check_if_repository_application_is_installed?owner=$owner&repo=$repo"; then
                echo "Repository application is installed."
              else
                echo "::error file=$file,title=Repository Check Failed::Repository check failed for $owner/$repo"
                failures+="\n- $owner/$repo"
                failed=1
              fi

            else
              echo "No valid allocation_bookkeeping GitHub URL in $file — skipping."
            fi
          done

          if [[ "$failed" -eq 1 ]]; then
            echo -e "::error title=Check Summary::One or more repository checks failed:\n$failures"
            exit 1
          else
            echo "All repository checks passed."
          fi

      - name: No relevant JSON files found
        if: ${{ steps.changed-files.outputs.any_changed == 'false' }}
        run: echo "No changed JSON files in Allocators/ — nothing to check."
